name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REGISTRY: us-central1-docker.pkg.dev
  REPO: devops-project

jobs:
  deploy-vote:
    name: Deploy Vote App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/vote:${{ github.sha }} \
            ./vote

      - name: Push Docker image
        run: |
          docker push \
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/vote:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy vote \
            --image ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/vote:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 80 \
            --vpc-connector voting-connector \
            --set-env-vars REDIS_HOST=10.190.65.43

  deploy-result:
    name: Deploy Result App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/result:${{ github.sha }} \
            ./result

      - name: Push Docker image
        run: |
          docker push \
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/result:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy result \
            --image ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/result:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 80 \
            --vpc-connector voting-connector \
            --set-env-vars "POSTGRES_HOST=34.173.141.233,POSTGRES_USER=voteuser,POSTGRES_PASSWORD=voting123,POSTGRES_DB=votes"